In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [6]:
SCRIPT_DIR_PATH = os.getcwd()
PARENT_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
DATA_DIR_PATH = os.path.join(PARENT_DIR_PATH, "data")
RAW_DATA_DIR_PATH = os.path.join(DATA_DIR_PATH, "raw_data")
PROCESSED_DATA_DIR_PATH = os.path.join(DATA_DIR_PATH, "processed_data")
CLIMATE_POLICY_DATA_DIR_PATH = os.path.join(RAW_DATA_DIR_PATH, "climate_policy_data")

In [7]:
emissions_df = pd.read_csv(os.path.join(PROCESSED_DATA_DIR_PATH, "historical_total_emission_per_country.csv"))
emissions_df.head()

  iso_alpha_3  year  total_emissions
0         ABW  1970         0.036970
1         ABW  1971         0.041825
2         ABW  1972         0.052708
3         ABW  1973         0.057704
4         ABW  1974         0.056999

## Climate Policy Database

In [9]:
cpd_df = pd.read_excel(os.path.join(CLIMATE_POLICY_DATA_DIR_PATH, "ClimatePolicyDatabase_v2023.xlsx"))
cpd_df.head()

,policy_id,country_iso,country_update,policy_title,policy_name,jurisdiction,supernational_region,country,subnational_region,policy_city_or_local,...,end_date,high_impact,policy_objective,reference,last_update,impact_indicators.comments,impact_indicators.name,impact_indicators.value,impact_indicators.base_year,impact_indicators.target_year
0,211000001,ITA,Sporadic,"""All inclusive"" Feed-in Tariff for small renew...","""All inclusive"" Feed-in Tariff for small renew...",Country,NaN,Italy,NaN,NaN,...,NaN,Unknown,Mitigation,https://www.iea.org/policies/4673-feed-in-tari...,NaT,NaN,NaN,NaN,NaN,NaN
1,211000002,DEU,Annual,"""Energy of the Future"" monitoring process Germ...","""Energy of the Future"" monitoring process",Country,NaN,Germany,NaN,NaN,...,NaN,Unknown,Mitigation,https://www.bmwi.de/Redaktion/EN/Artikel/Energ...,NaT,NaN,NaN,NaN,NaN,NaN
2,211000003,DEU,Annual,"""Energy-efficient Systems in Trade and Industr...","""Energy-efficient Systems in Trade and Industr...",Country,NaN,Germany,NaN,NaN,...,2007,Unknown,Mitigation,http://www.stromeffizienz.de/,NaT,NaN,NaN,NaN,NaN,NaN
3,211000004,FRA,Sporadic,"""Investment for the Future"" Programme France (...","""Investment for the Future"" Programme",Country,NaN,France,NaN,NaN,...,NaN,Unknown,Mitigation,https://www.iea.org/policies/3115-investment-f...,NaT,NaN,NaN,NaN,NaN,NaN
4,211000005,KOR,Annual,"""Kids ISO 14000 Program"" for Energy Conservati...","""Kids ISO 14000 Program"" for Energy Conservati...",Country,NaN,Republic of Korea,NaN,NaN,...,NaN,Unknown,Mitigation,http://www.iso.org/iso/en/kidsiso14000/index.html,NaT,NaN,NaN,NaN,NaN,NaN

In [12]:
fields_to_keep = [
    "country_iso",
    "policy_name",
    "jurisdiction",
    "policy_instrument",
    "policy_type",
    "policy_status",
    "decision_date",
    "end_date"
]

cpd_df_filtered = cpd_df[fields_to_keep]
cpd_df_filtered.head()

,country_iso,policy_name,jurisdiction,policy_instrument,policy_type,policy_status,decision_date,end_date
0,ITA,"""All inclusive"" Feed-in Tariff for small renew...",Country,"Feed-in tariffs or premiums, Green certificates",Renewables,Superseded,2008.0,NaN
1,DEU,"""Energy of the Future"" monitoring process",Country,"Policy support, Institutional creation, Strate...",Energy service demand reduction and resource e...,In force,2011.0,NaN
2,DEU,"""Energy-efficient Systems in Trade and Industr...",Country,Information and education,Energy efficiency,Ended,2004.0,2007
3,FRA,"""Investment for the Future"" Programme",Country,Infrastructure investments,Other low-carbon technologies and fuel switch,Ended,2014.0,NaN
4,KOR,"""Kids ISO 14000 Program"" for Energy Conservati...",Country,Information provision,Energy efficiency,In force,2005.0,NaN

In [13]:
cpd_df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6273 entries, 0 to 6272
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country_iso        6273 non-null   object
 1   policy_name        6273 non-null   object
 2   jurisdiction       6273 non-null   object
 3   policy_instrument  6273 non-null   object
 4   policy_type        6273 non-null   object
 5   policy_status      6273 non-null   object
 6   decision_date      6247 non-null   float64
 7   end_date           1464 non-null   object
dtypes: float64(1), object(7)
memory usage: 392.2+ KB

In [17]:
cpd_df_filtered.jurisdiction.unique()

array(['Country', 'Subnational region', 'City'], dtype=object)

In [14]:
cpd_df_filtered.country_iso.nunique()

199