In [22]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [23]:
curr_dir_path = os.getcwd()
main_dir_path = os.path.abspath(os.path.join(curr_dir_path, os.pardir))
data_dir_path = os.path.join(main_dir_path, 'data')
raw_data_dir_path = os.path.join(data_dir_path, 'raw_data')
processed_data_dir_path = os.path.join(data_dir_path, 'processed_data')
cw_dir_path = os.path.join(data_dir_path, 'cw')
emissions_data_dir_path = os.path.join(raw_data_dir_path, 'emissions_data')
iea_data_dir_path = os.path.join(raw_data_dir_path, 'IEA_climate_policy_data')

In [24]:
emissions_db = pd.read_csv(os.path.join(emissions_data_dir_path, 'CSC-GHG_emissions-April2024_to_calibrate.csv'), encoding='latin1')
emissions_db.head()

,Code,Country,EDGAR Country Code,Income group,Lending category,Region,CSC Sector,CSC Subsector,Gas,Units,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,ABW,Aruba,ABW,High income,NaN,Latin America & Caribbean,Energy,EN - Building,CH4,MtCO2e,...,0.000554,0.000538,0.000500,0.000570,0.000542,0.000574,0.000471,0.000616,0.000617,0.000622
1,ABW,Aruba,ABW,High income,NaN,Latin America & Caribbean,Energy,EN - Building,CO2,MtCO2e,...,0.047090,0.037332,0.035079,0.039403,0.035488,0.044616,0.050051,0.044068,0.042466,0.044068
2,ABW,Aruba,ABW,High income,NaN,Latin America & Caribbean,Energy,EN - Building,N2O,MtCO2e,...,0.000160,0.000138,0.000130,0.000137,0.000135,0.000235,0.000264,0.000240,0.000234,0.000241
3,ABW,Aruba,ABW,High income,NaN,Latin America & Caribbean,Energy,EN - Electricity/Heat,CH4,MtCO2e,...,0.000114,0.000120,0.000126,0.000127,0.000122,0.000132,0.000156,0.000135,0.000132,0.000136
4,ABW,Aruba,ABW,High income,NaN,Latin America & Caribbean,Energy,EN - Electricity/Heat,CO2,MtCO2e,...,0.213816,0.222204,0.229352,0.239740,0.223555,0.232325,0.274290,0.232537,0.224081,0.232537

In [25]:
emissions_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6624 entries, 0 to 6623
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Code                6624 non-null   object
 1   Country             6624 non-null   object
 2   EDGAR Country Code  6214 non-null   object
 3   Income group        6152 non-null   object
 4   Lending category    4273 non-null   object
 5   Region              6214 non-null   object
 6   CSC Sector          6624 non-null   object
 7   CSC Subsector       6624 non-null   object
 8   Gas                 6624 non-null   object
 9   Units               6624 non-null   object
 10  2000                6583 non-null   float64
 11  2001                6583 non-null   float64
 12  2002                6583 non-null   float64
 13  2003                6583 non-null   float64
 14  2004                6583 non-null   float64
 15  2005                6583 non-null   float64
 16  2006                6583 non-null   float64
 17  2007                6583 non-null   float64
 18  2008                6583 non-null   float64
 19  2009                6583 non-null   float64
 20  2010                6583 non-null   float64
 21  2011                6583 non-null   float64
 22  2012                6583 non-null   float64
 23  2013                6583 non-null   float64
 24  2014                6583 non-null   float64
 25  2015                6583 non-null   float64
 26  2016                6583 non-null   float64
 27  2017                6583 non-null   float64
 28  2018                6583 non-null   float64
 29  2019                6583 non-null   float64
 30  2020                6583 non-null   float64
 31  2021                6583 non-null   float64
 32  2022                6583 non-null   float64
dtypes: float64(23), object(10)
memory usage: 1.7+ MB

## Create a DB with total emissions data per country and year

In [26]:
total_em_db = emissions_db.drop(columns=['Country',
                                         'EDGAR Country Code',
                                         'Lending category',
                                         'Region',
                                         'CSC Sector',
                                         'CSC Subsector',
                                         'Gas',
                                         'Units'])
total_em_db.head()

,Code,Income group,2000,2001,2002,2003,2004,2005,2006,2007,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,ABW,High income,0.000202,0.000214,0.000218,0.000244,0.000263,0.000242,0.000218,0.000216,...,0.000554,0.000538,0.000500,0.000570,0.000542,0.000574,0.000471,0.000616,0.000617,0.000622
1,ABW,High income,0.021251,0.023579,0.023320,0.027214,0.032069,0.026398,0.019531,0.020556,...,0.047090,0.037332,0.035079,0.039403,0.035488,0.044616,0.050051,0.044068,0.042466,0.044068
2,ABW,High income,0.000218,0.000221,0.000195,0.000211,0.000249,0.000283,0.000234,0.000316,...,0.000160,0.000138,0.000130,0.000137,0.000135,0.000235,0.000264,0.000240,0.000234,0.000241
3,ABW,High income,0.000073,0.000075,0.000079,0.000091,0.000095,0.000101,0.000111,0.000126,...,0.000114,0.000120,0.000126,0.000127,0.000122,0.000132,0.000156,0.000135,0.000132,0.000136
4,ABW,High income,0.131217,0.133759,0.137867,0.166334,0.171255,0.196176,0.215872,0.245975,...,0.213816,0.222204,0.229352,0.239740,0.223555,0.232325,0.274290,0.232537,0.224081,0.232537

In [27]:
total_em_db = total_em_db.groupby(['Code', 'Income group']).sum().reset_index()

In [28]:
total_em_db.head()

,Code,Income group,2000,2001,2002,2003,2004,2005,2006,2007,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,ABW,High income,0.335765,0.344135,0.363222,0.412246,0.430187,0.462648,0.460574,0.500896,...,0.463848,0.475081,0.476461,0.494114,0.467189,0.502077,0.575822,0.494731,0.479192,0.496683
1,AFG,Low income,25.390391,23.723115,26.383509,27.071538,27.128799,27.530896,27.800600,28.957237,...,40.239394,40.553720,40.547614,39.906206,41.113739,40.780451,39.663300,37.490896,38.293652,38.457458
2,AGO,Lower middle income,111.523943,109.364994,108.114862,108.366595,114.489712,113.596505,106.468040,105.871055,...,153.402875,155.619124,160.471046,157.527001,152.294729,148.625339,147.845001,142.092103,140.023488,136.889648
3,ALB,Upper middle income,8.622689,8.813742,9.442418,9.634894,9.846009,9.439586,9.484936,9.441164,...,9.784391,10.175930,10.115224,9.730925,10.551144,10.499227,10.014283,9.132821,9.167750,9.252882
4,ARE,High income,118.058737,131.934048,132.985310,140.681731,147.191215,156.396070,164.025241,175.161269,...,246.490213,250.361456,264.297187,272.718853,262.553397,245.033116,260.261776,262.847956,278.324899,286.675891

In [29]:
# Change total_em_db to wide format
total_em_db_long = pd.melt(total_em_db, id_vars=['Code', 'Income group'], var_name='Year', value_name='Total Emissions')
total_em_db_long.sort_values(by=['Code', 'Year'], inplace=True)
total_em_db_long.reset_index(drop=True, inplace=True)

In [30]:
# make cols lowercase and replace spaces with underscores
total_em_db_long.columns = total_em_db_long.columns.str.lower().str.replace(' ', '_')

# rename 'code' to 'iso_alpha_3'
total_em_db_long.rename(columns={'code': 'iso_alpha_3'}, inplace=True)

total_em_db_long

     iso_alpha_3         income_group  year  total_emissions
0            ABW          High income  2000         0.335765
1            ABW          High income  2001         0.344135
2            ABW          High income  2002         0.363222
3            ABW          High income  2003         0.412246
4            ABW          High income  2004         0.430187
...          ...                  ...   ...              ...
4480         ZWE  Lower middle income  2018        47.509033
4481         ZWE  Lower middle income  2019        46.442562
4482         ZWE  Lower middle income  2020        44.576343
4483         ZWE  Lower middle income  2021        45.759664
4484         ZWE  Lower middle income  2022        46.423948

[4485 rows x 4 columns]

In [31]:
total_em_db_long.to_csv(os.path.join(processed_data_dir_path, 'total_emissions_db.csv'), index=False)