In [27]:
import pandas as pd
import os

In [28]:
CURR_DIR_PATH = os.getcwd()
MAIN_DIR_PATH = os.path.abspath(os.path.join(CURR_DIR_PATH, os.pardir))
DATA_DIR_PATH = os.path.join(MAIN_DIR_PATH, 'data')
RAW_DATA_DIR_PATH = os.path.join(DATA_DIR_PATH, 'raw_data')
PROCESSED_DATA_DIR_PATH = os.path.join(DATA_DIR_PATH, 'processed_data')
EMISSIONS_DATA_DIR_PATH = os.path.join(RAW_DATA_DIR_PATH, 'emissions_data')

## 1. Load EDGAR's Emission Data

In [29]:
emissions_df= pd.read_csv(os.path.join(EMISSIONS_DATA_DIR_PATH, 'EDGAR_Emission_Totals.csv'))
emissions_df.head()

,IPCC_annex,C_group_IM24_sh,Country_code_A3,Name,Substance,Y_1970,Y_1971,Y_1972,Y_1973,Y_1974,...,Y_2015,Y_2016,Y_2017,Y_2018,Y_2019,Y_2020,Y_2021,Y_2022,Y_2023,Y_2024
0,Non-Annex_I,Rest Central America,ABW,Aruba,GWP_100_AR5_GHG,36.969560,41.825240,52.708352,57.704309,56.999430,...,491.516428,515.073362,496.688325,494.966918,540.013489,519.080727,538.334799,567.492030,569.502788,588.716403
1,Non-Annex_I,India +,AFG,Afghanistan,GWP_100_AR5_GHG,15299.964080,15221.080240,13278.752230,13972.048750,15242.001770,...,28093.084620,27164.741410,30474.594820,31935.810420,32436.168450,32400.167960,32835.845920,31912.139080,32435.106740,33034.840090
2,Non-Annex_I,Southern_Africa,AGO,Angola,GWP_100_AR5_GHG,18834.350180,18721.849830,21316.779020,22878.757110,23586.100830,...,83536.857860,80625.507760,75433.642680,70465.116030,71208.749440,63159.221100,66601.919420,68035.237040,68280.785050,69922.938780
3,Non-Annex_I,Rest Central America,AIA,Anguilla,GWP_100_AR5_GHG,3.397521,3.447974,3.594584,3.480455,3.770682,...,31.417667,31.812681,32.560698,31.682045,31.036684,26.124833,25.313813,25.155856,25.157584,26.035166
4,Int. Aviation,Int. Aviation,AIR,Int. Aviation,GWP_100_AR5_GHG,172478.015800,172465.446700,182459.825500,190296.914800,183162.106100,...,543596.040800,567905.925700,597733.371500,623932.398500,633217.053500,299636.334300,330748.407500,477751.478000,578330.736500,622334.162100

In [30]:
emissions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 60 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IPCC_annex       225 non-null    object
 1   C_group_IM24_sh  225 non-null    object
 2   Country_code_A3  225 non-null    object
 3   Name             225 non-null    object
 4   Substance        225 non-null    object
 5   Y_1970           225 non-null    float64
 6   Y_1971           225 non-null    float64
 7   Y_1972           225 non-null    float64
 8   Y_1973           225 non-null    float64
 9   Y_1974           225 non-null    float64
 10  Y_1975           225 non-null    float64
 11  Y_1976           225 non-null    float64
 12  Y_1977           225 non-null    float64
 13  Y_1978           225 non-null    float64
 14  Y_1979           225 non-null    float64
 15  Y_1980           225 non-null    float64
 16  Y_1981           225 non-null    float64
 17  Y_1982           225 non-null    float64
 18  Y_1983           225 non-null    float64
 19  Y_1984           225 non-null    float64
 20  Y_1985           225 non-null    float64
 21  Y_1986           225 non-null    float64
 22  Y_1987           225 non-null    float64
 23  Y_1988           225 non-null    float64
 24  Y_1989           225 non-null    float64
 25  Y_1990           225 non-null    float64
 26  Y_1991           225 non-null    float64
 27  Y_1992           225 non-null    float64
 28  Y_1993           225 non-null    float64
 29  Y_1994           225 non-null    float64
 30  Y_1995           225 non-null    float64
 31  Y_1996           225 non-null    float64
 32  Y_1997           225 non-null    float64
 33  Y_1998           225 non-null    float64
 34  Y_1999           225 non-null    float64
 35  Y_2000           225 non-null    float64
 36  Y_2001           225 non-null    float64
 37  Y_2002           225 non-null    float64
 38  Y_2003           225 non-null    float64
 39  Y_2004           225 non-null    float64
 40  Y_2005           225 non-null    float64
 41  Y_2006           225 non-null    float64
 42  Y_2007           225 non-null    float64
 43  Y_2008           225 non-null    float64
 44  Y_2009           225 non-null    float64
 45  Y_2010           225 non-null    float64
 46  Y_2011           225 non-null    float64
 47  Y_2012           225 non-null    float64
 48  Y_2013           225 non-null    float64
 49  Y_2014           225 non-null    float64
 50  Y_2015           225 non-null    float64
 51  Y_2016           225 non-null    float64
 52  Y_2017           225 non-null    float64
 53  Y_2018           225 non-null    float64
 54  Y_2019           225 non-null    float64
 55  Y_2020           225 non-null    float64
 56  Y_2021           225 non-null    float64
 57  Y_2022           225 non-null    float64
 58  Y_2023           225 non-null    float64
 59  Y_2024           225 non-null    float64
dtypes: float64(55), object(5)
memory usage: 105.6+ KB

## 2. Create a CSV with total emissions data per country and year (long format)

In [31]:
emissions_df.columns

Index(['IPCC_annex', 'C_group_IM24_sh', 'Country_code_A3', 'Name', 'Substance',
       'Y_1970', 'Y_1971', 'Y_1972', 'Y_1973', 'Y_1974', 'Y_1975', 'Y_1976',
       'Y_1977', 'Y_1978', 'Y_1979', 'Y_1980', 'Y_1981', 'Y_1982', 'Y_1983',
       'Y_1984', 'Y_1985', 'Y_1986', 'Y_1987', 'Y_1988', 'Y_1989', 'Y_1990',
       'Y_1991', 'Y_1992', 'Y_1993', 'Y_1994', 'Y_1995', 'Y_1996', 'Y_1997',
       'Y_1998', 'Y_1999', 'Y_2000', 'Y_2001', 'Y_2002', 'Y_2003', 'Y_2004',
       'Y_2005', 'Y_2006', 'Y_2007', 'Y_2008', 'Y_2009', 'Y_2010', 'Y_2011',
       'Y_2012', 'Y_2013', 'Y_2014', 'Y_2015', 'Y_2016', 'Y_2017', 'Y_2018',
       'Y_2019', 'Y_2020', 'Y_2021', 'Y_2022', 'Y_2023', 'Y_2024'],
      dtype='object')

In [32]:
# Drop unnecessary columns
total_em_df = emissions_df.drop(columns=['IPCC_annex', 'C_group_IM24_sh', 'Name', 'Substance'])
total_em_df.head()

,Country_code_A3,Y_1970,Y_1971,Y_1972,Y_1973,Y_1974,Y_1975,Y_1976,Y_1977,Y_1978,...,Y_2015,Y_2016,Y_2017,Y_2018,Y_2019,Y_2020,Y_2021,Y_2022,Y_2023,Y_2024
0,ABW,36.969560,41.825240,52.708352,57.704309,56.999430,71.134019,70.200482,81.045397,85.917158,...,491.516428,515.073362,496.688325,494.966918,540.013489,519.080727,538.334799,567.492030,569.502788,588.716403
1,AFG,15299.964080,15221.080240,13278.752230,13972.048750,15242.001770,15968.871860,16124.560870,16187.782750,15833.413130,...,28093.084620,27164.741410,30474.594820,31935.810420,32436.168450,32400.167960,32835.845920,31912.139080,32435.106740,33034.840090
2,AGO,18834.350180,18721.849830,21316.779020,22878.757110,23586.100830,22421.772220,18464.447180,23132.615150,25307.983690,...,83536.857860,80625.507760,75433.642680,70465.116030,71208.749440,63159.221100,66601.919420,68035.237040,68280.785050,69922.938780
3,AIA,3.397521,3.447974,3.594584,3.480455,3.770682,4.050930,3.920464,4.052564,4.449552,...,31.417667,31.812681,32.560698,31.682045,31.036684,26.124833,25.313813,25.155856,25.157584,26.035166
4,AIR,172478.015800,172465.446700,182459.825500,190296.914800,183162.106100,177165.834400,177483.078200,193593.366500,200750.193500,...,543596.040800,567905.925700,597733.371500,623932.398500,633217.053500,299636.334300,330748.407500,477751.478000,578330.736500,622334.162100

In [33]:
# Change total_em_db to wide format
total_em_df_long = pd.melt(total_em_df, id_vars=['Country_code_A3'], var_name='Year', value_name='Total Emissions')
total_em_df_long.sort_values(by=['Country_code_A3', 'Year'], inplace=True)
total_em_df_long.reset_index(drop=True, inplace=True)
total_em_df_long.head()

  Country_code_A3    Year  Total Emissions
0             ABW  Y_1970        36.969560
1             ABW  Y_1971        41.825240
2             ABW  Y_1972        52.708352
3             ABW  Y_1973        57.704309
4             ABW  Y_1974        56.999430

In [35]:
# make cols lowercase and replace spaces with underscores
total_em_df_long.columns = total_em_df_long.columns.str.lower().str.replace(' ', '_')

# rename 'country_code_a3' to 'iso_alpha_3'
total_em_df_long.rename(columns={'country_code_a3': 'iso_alpha_3'}, inplace=True)

total_em_df_long

      iso_alpha_3    year  total_emissions
0             ABW  Y_1970        36.969560
1             ABW  Y_1971        41.825240
2             ABW  Y_1972        52.708352
3             ABW  Y_1973        57.704309
4             ABW  Y_1974        56.999430
...           ...     ...              ...
12370         ZWE  Y_2020     24793.786060
12371         ZWE  Y_2021     27149.709490
12372         ZWE  Y_2022     28025.626830
12373         ZWE  Y_2023     30124.984830
12374         ZWE  Y_2024     30784.272450

[12375 rows x 3 columns]

In [36]:
# Remove prefix to year field
total_em_df_long["year"] = total_em_df_long["year"].str.replace("Y_", "", regex=False).astype(int)

# Convert total emissions from Gg to Mt
total_em_df_long["total_emissions"] = total_em_df_long["total_emissions"] / 1000.0
total_em_df_long

      iso_alpha_3  year  total_emissions
0             ABW  1970         0.036970
1             ABW  1971         0.041825
2             ABW  1972         0.052708
3             ABW  1973         0.057704
4             ABW  1974         0.056999
...           ...   ...              ...
12370         ZWE  2020        24.793786
12371         ZWE  2021        27.149709
12372         ZWE  2022        28.025627
12373         ZWE  2023        30.124985
12374         ZWE  2024        30.784272

[12375 rows x 3 columns]

In [39]:
print("Unique iso_alpha_3 count:", total_em_df_long["iso_alpha_3"].nunique())
print("Year range:", total_em_df_long["year"].min(), "to", total_em_df_long["year"].max())

Unique iso_alpha_3 count: 225
Year range: 1970 to 2024

In [37]:
total_em_df_long.to_csv(os.path.join(PROCESSED_DATA_DIR_PATH, 'historical_total_emission_per_country.csv'), index=False)